openapi: "3.0.0"

info:
    title: "PowerMeter API"
    version: "1.0.0"
    description: "API für von Messwerten, Verlaufsdaten, Logdateien und Kofigurationen"

servers:
    - url: "{ip}/api"
      description: "STA Modus"
    - url: "192.168.4.1/api"
      description: "AP Modus"

paths:
    /momentary:
        get:
            summary: "Momentane Messwerte auslesen"
            responses:
                200:
                    description: "Json Objekt mit den Messwerten"
                    content:
                        application/json:
                            schema:
                                type: "object"
                                properties:
                                    voltage:
                                        type: "number"
                                    current:
                                        type: "number"
                                    active:
                                        type: "number"
                                    apparent:
                                        type: "number"
                                    reactive:
                                        type: "number"
                                    factor:
                                        type: "number"

    /last24h:
        get:
            summary: "Verlauf der letzten 24h auslesen"
            responses:
                200:
                    description: "Json Array mit den durchschnittlichen Messwerten der letzten 24 Stunden"
                    content:
                        application/json:
                            schema:
                                type: "array"
                                items:
                                    type: number

    /config:
        get:
            summary: "Kofiguration auslesen"
            responses:
                200:
                    description: "Zustand des Relais als boolscher Wert"
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/config"
        put:
            summary: "Kofiguration setzen"
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/config"
            responses: 
                200:
                    description: "Kofiguration aktualisiert"
                
components:
    schemas:
        config:
            type: "object"
            properties:
                name: 
                    type: "string"
                    maxLength: 30
                relay:
                    type: "boolean"
                logging:
                    type: "object"
                    properties:
                        level:
                            type: "integer"
                            minimum: 0
                            maximum: 6
                        filemode:
                            type: "boolean"
                calibration: 
                    type: "object"
                    properties:
                        voltage: 
                            type: "number"
                        current: 
                            type: "number"
                        phase:
                            type: "number"
                    required: 
                        - "voltage"
                        - "current"
                        - "phase"
                wifi:
                    type: "object"
                    properties:
                        apmode:
                            type: "boolean"
                        sta:
                            type: "object"
                            properties:
                                ssid:
                                    type: "string"
                                    minLength: 2
                                    maxLength: 32
                                password:
                                    type: "string"
                                    minLength: 8
                                    maxLength: 63
                                staticip:
                                    type: "string"
                                    format: "ipv4"
                                gateway:
                                    type: "string"
                                    format: "ipv4"
                                subnet:
                                    type: "string"
                                    format: "ipv4"
                                dns1:
                                    type: "string"
                                    format: "ipv4"
                                dns2:
                                    type: "string"
                                    format: "ipv4"
                        ap:
                            type: "object"
                            properties:
                                ssid:
                                    type: "string"
                                    minLength: 2
                                    maxLength: 32
                                password:
                                    type: "string"
                                    minLength: 8
                                    maxLength: 63
                                    
                    

